### ISSUE TITLE
fedy-plugins-developers repo/package?

### ISSUE THREAD

**Issue by user501254** [folkswithhats/fedy-plugins-developers#15]
It's a thought.
Would it be a good thing to have a repo/package for adding extra plugins to Fedy?

**Comment by Abhinav1217** [comment]
Fedy cant be bundled all the plugins because list would be too long. Lots of IDEs and Browsers, and apps. Therefore this repo was created to separate plugins from app itself, which in turn separated  pull requests for fedy app and fedy plugins.  You can download any plugin from here and put the folder into `~/.local/share/fedy/plugins` to use it. Popular plugins are bundled with fedy release. 

We are discussing several different approach to improve plugin experience in fedy.  End goal is to ease of installing extra plugins.
